function cfg = project238Config(root)
%PROJECT238CONFIG Full official training by default; CPU and bounded input.
    if nargin < 1, root = fileparts(mfilename('fullpath')); end
    cfg = struct('rootDir',root,'rawDir',fullfile(root,'data'), ...
        'dataDir',fullfile(root,'data','project238'), ...
        'outputDir',fullfile(root,'runs','project238_full_seed_101'), ...
        'trainCount',Inf,'validationCount',10000,'testCount',Inf, ...
        'chunkRows',2000,'imageSize',32,'epochs',12,'batchSize',64, ...
        'seed',101,'executionEnvironment','cpu');
end
